### ISSUE TITLE
Is there a way to persistently enforce the setting?

### ISSUE THREAD

**Issue by lucisac** [BepInEx/BepInEx.GraphicsSettings#1]
Hi there, this mod works great but is it possible to add a setting to keep the resolution enabled as when changing scenes in the game it reverts back to the in-game set resolution which the developers only enabled up to 1080p max.

Game: Machina of the Planet Tree -Unity Unions

Thanks in advance!

**Comment by Keelhauled** [comment]
The plugin was only intended for games that don't manage their own graphics settings. Mainly because there is a million ways a game could reset or change those settings so catching all of them would be impossible in a generic plugin. That's why it's better to make a game specific plugin to change that behaviour.

**Comment by lucisac** [comment]
Hi Keelhauled, thanks for the prompt reply.  Do you know of any forum where I could get request such mod to be commissioned? It' a very small game with almost 0 players so no one has made mods for it.

**Comment by Keelhauled** [comment]
Sorry, I don't know any forums for that.

**Comment by lucisac** [comment]
Are you available for hire?
Or maybe it would be possible to add a shortcut to reapply resolution in the mod setting (as that stays on the desired setting), that would work too.

**Comment by lucisac** [comment]
Actually, it seems I was able to use dnspy and edit some setresolution parameters!  Thank you for your time, your mod inspired me to look deeper!

this.resolution = value;
				switch (this.resolution)
				{
				case GameManager.ScreenResolution.W2560_H1440:
					Screen.SetResolution(2560, 1440, Screen.fullScreen);
