### ISSUE TITLE
Studio Fullscreen settings not completely followed upon loading

### ISSUE THREAD

**Issue by atnilla** [BepInEx/BepInEx.GraphicsSettings#3]
Expected behavior: Loading Studio/Koikatsu with borderless fullscreen settings would load but also not automatically minimize the window when clicking outside of the window to, for example, drag and drop a card from a folder into the studio or game.

Actual behavior: Loading Studio/Koikatsu loads in borderless fullscreen, but clicking out of window minimizes studio/game. Have noticed that Studio loading screen will be in perfect Borderless Fullscreen, but when that loading window closes the usable window is no longer the borderless fullscreen.

Temporary fix: opening config menu with F1 and manually changing from borderless fullscreen to anything else, and then back to borderless fullscreen will keep the studio from automatically minimizing, but will also disable the ability to drag and drop cards into studio/game. Problem with window settings will persist upon next load of studio of game. 

Troubleshooting steps taken so far in order after each failed fix: 
Unchecked box in InitSetting and loaded game, changes graphics to default
Loaded game from Initsetting
Rechecked box in initsetting and reloaded studio
Loaded studio from taskbar
Unchecked box in InitSetting and loaded game, changed graphics settings to fullscreen
Loaded studio in fullscreen
Left box unchecked and loaded from InitSetting, changed graphics to windowed
Loaded studio in windowed

At this point I dont know if its my computers own graphics settings, the graphics settings plugin, the config plugin, or ghosts in my circuitry, but this problem has plagued me on two completely different computers' hardware. This issue is so persistent that if video of how it works would help I can record it easily and readily.

**Comment by Keelhauled** [comment]
Try deleting the SettingsVerifier plugin and see if it gets fixed. That thing is a pain

**Comment by atnilla** [comment]
> Try deleting the SettingsVerifier plugin and see if it gets fixed. That thing is a pain

Well the windows don't automatically minimize when they're not focused, but they still don't open into borderless fullscreen, whether or not the "Play game in fullscreen" is checked in Initsettings. So thats one problem fixed, whcih was already getting fixed when manually doing window settings every single load.

**Comment by Keelhauled** [comment]
Try deleting setup.xml in userdata and not using the launcher or SettingsVerifier. That's what I do and everything works for me.

**Comment by atnilla** [comment]
> Try deleting setup.xml in userdata and not using the launcher or SettingsVerifier. That's what I do and everything works for me.

Doing that and cycling through graphics settings, Default loads a full resolution window that sits behind the task bar, fullscreen goes straight into fullscreen but minimizes when out of the window, and borderless fullscreen loads a windowed full resolution that will sit in front of or behind the taskbar depending on wether im tabbed into it or not, and windowed does the same as default.

**Comment by Keelhauled** [comment]
Sounds like everything works correctly then, what are you expecting?

**Comment by atnilla** [comment]
Everything is not working correctly, though. Everything, except for borderless fullscreen, seems to function as they should, however borderless fullscreen does not automatically load as the other options do, which requires a manual fix on every load of the studio or game, but also breaks a handful of other plugins after doing the manual window mode change.

There was a point a year or two ago where borderless fullscreen worked exactly as it should and there were never any issues, up until at some point when my hard drive fried and I had to start from scratch with new everything. At some point between the last update I did before my hard drive died, and reinstalling everything fresh, something with borderless fullscreen broke and it fails to automatically set itself properly upon loading.

**Comment by Keelhauled** [comment]
If you got the repack or HF patch they come with GraphicsSettings broken just like you are describing. But doing the steps I mentioned should fix it. A video would help understand if it's something different.

**Comment by atnilla** [comment]
https://github.com/BepInEx/BepInEx.GraphicsSettings/assets/6482501/043773b3-9987-478b-970c-869df17e58f8

Not sure of exactly what you wanted to see, but this is how it goes when opening.

**Comment by Keelhauled** [comment]
Could be the EnableResize plugin messing with the borders. Try removing that as well.

**Comment by atnilla** [comment]
Yep, that was it, That plugin never occurred to me, not even quite sure what it does, regardless, thanks for the help, I appreciate it.
